### ISSUE TITLE
wrong logo on blade.php files

### ISSUE THREAD

**Issue by LeonMunene** [onecentlin/laravel-extension-pack-vscode#12]
I created a 'blade.php' file but the logo beside the file is the php logo instead of the laravel logo.Might the issue be a bug with new update of the laravel extension pack or my end.

**Comment by onecentlin** [comment]
@LeonMunene Please choose theme extension that recognize `.blade.php` as Laravel related file. e.g. [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)

Since theme extension is more personal preference, it's better not include in extension pack by default. ^^
